### ISSUE TITLE
转换时的警告

### ISSUE THREAD

**Issue by JiaPai12138** [hpc203/yolov5-dnn-cpp-python-v2#11]
TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!

相关代码：route = F.interpolate(xRt2, size=(int(xRt2.shape[2] * 2), int(xRt2.shape[3] * 2)), mode='nearest')

大佬 请问这个警告影响推理吗？

**Comment by hpc203** [comment]
不影响的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月9日(周四) 上午7:42
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [hpc203/yolov5-dnn-cpp-python-v2] 转换时的警告 (Issue #11)




 
TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
 
相关代码：route = F.interpolate(xRt2, size=(int(xRt2.shape[2] * 2), int(xRt2.shape[3] * 2)), mode='nearest')
 
大佬 请问这个警告影响推理吗？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JiaPai12138** [comment]
谢谢解答
